from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(714, 583)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tablelist = QtWidgets.QComboBox(self.centralwidget)
        self.tablelist.setGeometry(QtCore.QRect(380, 10, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tablelist.setFont(font)
        self.tablelist.setObjectName("tablelist")
        self.show_but = QtWidgets.QPushButton(self.centralwidget)
        self.show_but.setGeometry(QtCore.QRect(590, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.show_but.setFont(font)
        self.show_but.setObjectName("show_but")
        self.data_here = QtWidgets.QTableWidget(self.centralwidget)
        self.data_here.setGeometry(QtCore.QRect(20, 11, 341, 351))
        self.data_here.setObjectName("data_here")
        self.data_here.setColumnCount(0)
        self.data_here.setRowCount(0)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(380, 60, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.add_but = QtWidgets.QPushButton(self.centralwidget)
        self.add_but.setGeometry(QtCore.QRect(590, 60, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.add_but.setFont(font)
        self.add_but.setObjectName("add_but")
        self.del_but = QtWidgets.QPushButton(self.centralwidget)
        self.del_but.setGeometry(QtCore.QRect(590, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.del_but.setFont(font)
        self.del_but.setObjectName("del_but")
        self.plot_but_1 = QtWidgets.QPushButton(self.centralwidget)
        self.plot_but_1.setGeometry(QtCore.QRect(370, 150, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.plot_but_1.setFont(font)
        self.plot_but_1.setObjectName("plot_but_1")
        self.plot_but_2 = QtWidgets.QPushButton(self.centralwidget)
        self.plot_but_2.setGeometry(QtCore.QRect(480, 150, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.plot_but_2.setFont(font)
        self.plot_but_2.setObjectName("plot_but_2")
        self.plot_but_3 = QtWidgets.QPushButton(self.centralwidget)
        self.plot_but_3.setGeometry(QtCore.QRect(590, 150, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.plot_but_3.setFont(font)
        self.plot_but_3.setObjectName("plot_but_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 714, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Лабораторная работа №4"))
        self.show_but.setText(_translate("MainWindow", "Показать"))
        self.add_but.setText(_translate("MainWindow", "Добавить"))
        self.del_but.setText(_translate("MainWindow", "Удалить"))
        self.plot_but_1.setText(_translate("MainWindow", "Зарплата"))
        self.plot_but_2.setText(_translate("MainWindow", "Возраст"))
        self.plot_but_3.setText(_translate("MainWindow", "Премия"))
